#!/usr/bin/bash 

module purge
module load 2022
module load Python/3.10.4-GCCcore-11.3.0
module load scikit-build/0.11.1-foss-2022a
module load OpenSSL/1.1
module load TensorFlow/2.11.0-foss-2022a-CUDA-11.7.0
module load matplotlib/3.5.2-foss-2022a
python -m pip install --upgrade pip
pip install -U scikit-learn
pip install -U duckdb


